# syntax=docker/dockerfile:1.5

ARG PYTHON_VER=${PYTHON_VER:-3.10.8}

FROM python:${PYTHON_VER}

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ENV POSTGRES_USER=${POSTGRES_USER:-postgres}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-supereffectivesecret}
ENV POSTGRES_DB=${POSTGRES_DB:-postgres}
ENV POSTGRES_HOST=${POSTGRES_HOST:-localhost}
ENV POSTGRES_PORT=${POSTGRES_PORT:-5432}

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY . .

# ENTRYPOINT ["python", "/app/app.py"]
# CMD ["sh", "-c", "sleep infinity"]
CMD ["gunicorn", "--conf", "/app/gunicorn.conf.py", "--bind", "0.0.0.0:8000", "app:app"]
